=== Incredimed/client-registry/MARC.HI.EHRS.CR.Notification.PixPdq/Configuration/marc.hi.ehrs.cr.notification.pixpdq.xsd
<?xml version="1.0" encoding="utf-8"?>

<!--

  Copyright 2012-2013 Mohawk College of Applied Arts and Technology
  
  Licensed under the Apache License, Version 2.0 (the "License"); you 
  may not use this file except in compliance with the License. You may 
  obtain a copy of the License at 
  
  http://www.apache.org/licenses/LICENSE-2.0 
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
  License for the specific language governing permissions and limitations under 
  the License.
  
  User: fyfej
  Date: 21-8-2012


-->

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="ActionType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Any"/>
      <xs:enumeration value="Create"/>
      <xs:enumeration value="Update"/>
      <xs:enumeration value="DuplicatesResolved"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ActorType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="PAT_IDENTITY_X_REF_MGR"/>
      <xs:enumeration value="PAT_IDENTITY_SRC"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="marc.hi.ehrs.cr.notification.pixpdq">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="targets" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="add" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="notify">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="action" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="type" type="ActionType" use="required" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="domain" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="connectionString" type="xs:string" use="required" />
                  <xs:attribute name="name" type="xs:string" use="required" />
                  <xs:attribute name="myActor" type="ActorType" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="concurrencyLevel" type="xs:int" default="1"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Incredimed/client-registry/MARC.HI.EHRS.CR.Presentation/NotificationsConfig.xml
<marc.hi.ehrs.cr.notification.pixpdq xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file://./Configuration/marc.hi.ehrs.cr.notification.pixpdq.xsd">
  <targets>
    <add connectionString="llp://192.168.1.120:3602" deviceId="OPENXDS|ALLSCRIPTS" name="OpenXDS" myActor="PAT_IDENTITY_SRC">
      <notify domain="1.2.103.430.203.102.403.0">
        <action type="Any"/>
      </notify>
    </add>
    <add connectionString="llp://127.0.0.1:9100" deviceId="TS_SCE" name="MARC-HI XDS Registry" myActor="PAT_ID_X_REF_MGR">
    
      <!-- NB: this is for testing only, change this to match the affinity domain of the XDS repository -->
      <!--<trustedIssuerCertificate storeLocation="My" storeName="Root" x509FindType="FindByThumbprint" findValue=""/>
        <clientLLPCertificate storeLocation="My" storeName="Root" x509FindType="FindByThumbprint" findValue=""/>-->
      <notify domain="1.2.103.430.203.102.403.0">
        <action type="Any"/>
      </notify>
    </add>
  </targets>
</marc.hi.ehrs.cr.notification.pixpdq>
